[package]
name = "sonus-auris-sidecar"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "k8s sidecar for Sonus Auris."
repository = "https://github.com/sonus-auris/sonus-auris-sidecar.rs"
readme = "README.md"

[[bin]]
name = "sonus-auris-sidecar"
path = "src/main.rs"

[dependencies]
ores-otel-sidecar = { git = "https://github.com/ores-otel/ores-otel-sidecar.rs", rev = "fed785ad9a638e24d458e0f2acd390624e4e748d" }


[lints.rust]
unsafe_code = "forbid"
